[package]
name = "cch23-thewondersmith"
version = "0.0.1"
edition = "2021"

[dependencies]

url = "^2"
http = "^1.0"
anyhow = "^1"
axum = "^0.6"
visible = "*"
futures = "^0.3"
tracing = "^0.1"
thiserror = "^1"
serde_json = "^1"
itertools = "^0.12"
shuttle-axum = "^0.34"
shuttle-runtime = "^0.34"
tokio = { version = "^1.34", features = ["full"] }

[dev-dependencies]

rand = "^0.8"
regex = "^1.8"
rstest = "^0.18"
test-log = "^0.2"
once_cell = "^1.17"
tokio-test = "^0.4"
env_logger = "^0.10"
pretty_assertions = "^1.3"


[features]

ci = []
default = []
