# [Cocogitto](https://docs.cocogitto.io/) Configuration

from_latest_tag = false
ignore_merge_commits = false
branch_whitelist = [ "main", "release/**" ]
pre_bump_hooks = [
    # "cargo doc",
    # "cargo +nightly tarpaulin --packages cch23-thewondersmith --no-dead-code --no-fail-fast --fail-under=75",
    "cargo build --release --package cch23-thewondersmith",
    "echo 'bumping from {{latest}} to {{version}}'",
    "cargo bump {{version}}",
]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[commit_types]
hotfix = { changelog_title = "Hotfixes" }
release = { changelog_title = "Releases" }
wip = { changelog_title = "Work In Progress", omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
